Default: &defaults
  database: Personal.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Personal_test.sqlite3
  <<: *defaults

Staging:
  database: Personal_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: Personal_production.sqlite3
  poolsize: 100
  <<: *defaults
